### ISSUE TITLE
Integration and Averaging sensor

### ISSUE THREAD

**Issue by cail** [hobdrive/hobd#2]
## IntegrationSensor

IntegrationSensor(string base, int interval, int slotsCount)

This sensor tracks values of "base" sensor and integrates them into sum value using two different approaches.
### Unlimited sum

if `interval` is 0, average value is just recalculated based on total number of base sensor value updates.
I.e.

```
sum = sum + (base.Value) / TimeDiffFromPreviousIndication;
updateCount++;
Value = sum;
```
### Limited sum

if `interval` is not zero, it then means sum interval in milliseconds. All the data older than this interval is discarded from summary value.
Intermediate interval sum values are used to implement this, they should be stored in `timeslots[SlotsCount]`. Each slot is therefore aggregates data for `ainterval/SlotsCount` time.
Total value is:

```
Value = timeslots.Sum();
```

SlotsCount by default is 50.

There should also be `updateCountSlots[SlotsCount]`. The should count received sensor updates in each of the slots.
### Extra requirements

Sensor should be IAccumulatorSensor.

Limited average should be implemented as in FuelEconomy_short.
## AverageSensor

AverageSensor uses IntegrationSensor and uses `updateCount` to calculate:

```
Value = timeslots.Sum() / updateCountSlots.Sum();
```

AverageSensor is essentially  an `IntegrationSensor.Value / UpdateCount`
## TODO

Merge with FuelEconomy_short implementation?

FuelEconomy_short is IntegrationSensor(FuelConsumed, 60000) / IntegrationSensor(Speed, 60000)
etc...
## Test cases

// test sensor
var speedSensor = new CoreSensorEx("Test","Speed", "km");
var distanceSensor = new IntegrationSensor("Speed");
// assume we manually trigger "Speed" data
speedSensor.Update(0);
sleep(1hour);
speedSensor.Update(10);
sleep(2hour);
speedSensor.Update(20);
Assert.Equal(distanceSensor.Value, 10 + 20*2)

// distance we passed during the last 60 seconds
var distanceSensor = new IntegrationSensor("Speed", 60);
// TBD

**Comment by kolalex** [comment]
Значения от базового сенсора приходят через равные временные интервалы или произвольные ? Если произвольные, то среднее значение нужно подсчитывать с учетом временных интервалов.

**Comment by cail** [comment]
Интервалы от базового сенсора не равные - в зависимости от внешних обстоятельство они могут быть в общем-то любыми.

Да, среднеее нужно считать в общем-то деля общую сумму на общее время.
